/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mini_pos.dao.ui;

import java.awt.Image;
import java.awt.Point;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



/**
 *
 * @author User
 */
public class LoginDiaBox extends javax.swing.JFrame {

    /**
     * Creates new form Password
     */
	
	private boolean loginSucceeded = false;
    private ImageIcon eyeIcon;
    private ImageIcon eyeHideIcon;
	private boolean passwordHidden = true;
	
     private javax.swing.JLabel lblEye;
	
    public LoginDiaBox() {
        initComponents();
       
        initPasswordFeatures();   // Enable eye toggle
        
        
    }
    
    public void loginForm() { //setup dlglogin box 
    	dialogin.setModal(true);// this code mean another step will appear only if this box close
    	dialogin.pack();
    	dialogin.setLocationRelativeTo(this); // center
    	Point location = dialogin.getLocation();
    	dialogin.setLocation(location.x + 10, location.y + 10); // shift
    	dialogin.setVisible(true);
    }
    
    private void login() { // login function when click login button take input String from textbox and check with UserDAO loginUser
		try 
    	{
    		String username = this.txtusername.getText();
    		String password = this.txtpassword.getText();
    		boolean loginResult = txtusername.getText().equals("Admin") && txtpassword.getText().equals("Admin") ;
    		System.out.println("LoginResult " + loginResult +username + " " + password);
    		if(loginResult)
    		{
    			 this.loginSucceeded = true;
    			this.dialogin.setVisible(false);
    		}
    		else
    		{
    			JOptionPane.showMessageDialog(this, "Invalid User", "Warnning", JOptionPane.CLOSED_OPTION);
    		}
    	}
    	catch(Exception e)
    	{
    		JOptionPane.showMessageDialog(this, "Invalid User", "Warnning", JOptionPane.CLOSED_OPTION);
    	}
	}

    private ImageIcon resizeIcon(ImageIcon icon, int w, int h) {
        Image img = icon.getImage().getScaledInstance(w, h, Image.SCALE_SMOOTH);
        return new ImageIcon(img);
    }

    public void initPasswordFeatures() {
    	   eyeIcon = resizeIcon(new ImageIcon(getClass().getResource("/static/logo/show.png")), 20, 20);
    	    eyeHideIcon = resizeIcon(new ImageIcon(getClass().getResource("/static/logo/hide.png")), 20, 20);

        labeleye.setIcon(eyeHideIcon);     // start with password hidden
        txtpassword.setEchoChar('•');    // hide password

        labeleye.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                togglePassword();
            }
        });
    }
    
    private void togglePassword() {
        if (passwordHidden) {
        	txtpassword.setEchoChar((char) 0);  // show password
        	labeleye.setIcon(eyeIcon);
            passwordHidden = false;
        } else {
        	txtpassword.setEchoChar('•');       // hide password
        	labeleye.setIcon(eyeHideIcon);
            passwordHidden = true;
        }
    }

    
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogin = new javax.swing.JDialog();
        panellogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        btnlogin = new javax.swing.JButton();
        btnregister = new javax.swing.JButton();
        labeleye = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        diaregister = new javax.swing.JDialog();
        panelregister = new javax.swing.JPanel();
        labelregusername = new javax.swing.JLabel();
        labelregconfirmpassword = new javax.swing.JLabel();
        labelregpassword = new javax.swing.JLabel();
        txtregcomfirmpassword = new javax.swing.JTextField();
        txtregusername = new javax.swing.JTextField();
        txtregpassword = new javax.swing.JTextField();
        btnregregister = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        panellogin.setBackground(new java.awt.Color(250, 250, 250));
        panellogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 250, 250), 2));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("UserName");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Password");

        btnlogin.setForeground(new java.awt.Color(250, 250, 250));
        btnlogin.setText("Login");
        btnlogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });

        btnregister.setText("Register");

        javax.swing.GroupLayout panelloginLayout = new javax.swing.GroupLayout(panellogin);
        panellogin.setLayout(panelloginLayout);
        panelloginLayout.setHorizontalGroup(
            panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelloginLayout.createSequentialGroup()
                .addGroup(panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelloginLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtusername, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                            .addComponent(txtpassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labeleye, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelloginLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnregister, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(btnlogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        panelloginLayout.setVerticalGroup(
            panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelloginLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labeleye, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(btnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnregister, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialoginLayout = new javax.swing.GroupLayout(dialogin.getContentPane());
        dialogin.getContentPane().setLayout(dialoginLayout);
        dialoginLayout.setHorizontalGroup(
            dialoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panellogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dialoginLayout.setVerticalGroup(
            dialoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panellogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelregister.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 250, 250), 2));

        labelregusername.setText("Username");

        labelregconfirmpassword.setText("Confirm Password");

        labelregpassword.setText("Password");

        btnregregister.setText("Register");

        javax.swing.GroupLayout panelregisterLayout = new javax.swing.GroupLayout(panelregister);
        panelregister.setLayout(panelregisterLayout);
        panelregisterLayout.setHorizontalGroup(
            panelregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelregisterLayout.createSequentialGroup()
                .addGroup(panelregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelregisterLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelregisterLayout.createSequentialGroup()
                                .addComponent(labelregpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtregpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelregisterLayout.createSequentialGroup()
                                .addComponent(labelregconfirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtregcomfirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelregisterLayout.createSequentialGroup()
                                .addComponent(labelregusername, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtregusername, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelregisterLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnregregister, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        panelregisterLayout.setVerticalGroup(
            panelregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelregisterLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(panelregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelregusername, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtregusername, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(panelregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelregpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtregpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(panelregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelregconfirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtregcomfirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(btnregregister)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout diaregisterLayout = new javax.swing.GroupLayout(diaregister.getContentPane());
        diaregister.getContentPane().setLayout(diaregisterLayout);
        diaregisterLayout.setHorizontalGroup(
            diaregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaregisterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelregister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        diaregisterLayout.setVerticalGroup(
            diaregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaregisterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelregister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Password hide Complete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(432, 432, 432)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(442, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(240, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
    	this.login();
    }//GEN-LAST:event_btnloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    	
    	
    	  java.awt.EventQueue.invokeLater(new Runnable() {
              public void run() {
              	 // 1. Create the login dialog (modal)
                  LoginDiaBox mainFrame = new LoginDiaBox(); // create instance to pass as parent
                 
                  mainFrame.loginForm();
                  

//                  mainFrame.dlgLogin.setDefaultCloseOperation(javax.swing.JDialog.DO_NOTHING_ON_CLOSE);
//                  mainFrame.dlgLogin.addWindowListener(new java.awt.event.WindowAdapter() {
//                      @Override
//                      public void windowClosing(java.awt.event.WindowEvent e) {
//                          System.exit(0); // close program if user presses X
//                      }
//                  });


                  // check if dlgLogin is still visible   
                  if (mainFrame.loginSucceeded) {
                      mainFrame.setVisible(true);
                  } else {
                      System.exit(0);
                  }    
              }
              
          });
    	
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginDiaBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginDiaBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginDiaBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginDiaBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnregister;
    private javax.swing.JButton btnregregister;
    private javax.swing.JDialog dialogin;
    private javax.swing.JDialog diaregister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labeleye;
    private javax.swing.JLabel labelregconfirmpassword;
    private javax.swing.JLabel labelregpassword;
    private javax.swing.JLabel labelregusername;
    private javax.swing.JPanel panellogin;
    private javax.swing.JPanel panelregister;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtregcomfirmpassword;
    private javax.swing.JTextField txtregpassword;
    private javax.swing.JTextField txtregusername;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}


